CREATE SEQUENCE team_id_seq START WITH 1;

CREATE TABLE teams (
    uuid UUID PRIMARY KEY,
    id BIGINT NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL UNIQUE,
    country VARCHAR(100) NOT NULL,
    coach VARCHAR(200) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);