CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,

    home_score SMALLINT NOT NULL DEFAULT 0,
    away_score SMALLINT NOT NULL DEFAULT 0,

    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',

    CONSTRAINT fk_matches_home_team
        FOREIGN KEY (home_team_id) REFERENCES teams (id),

    CONSTRAINT fk_matches_away_team
        FOREIGN KEY (away_team_id) REFERENCES teams (id),

    CONSTRAINT chk_matches_different_teams
        CHECK (home_team_id <> away_team_id),

    CONSTRAINT chk_matches_home_score
        CHECK (home_score >= 0),

    CONSTRAINT chk_matches_away_score
        CHECK (away_score >= 0),

    CONSTRAINT chk_matches_status
        CHECK (
            status IN (
                'SCHEDULED',
                'LIVE',
                'HALFTIME',
                'FINISHED',
                'CANCELLED'
            )
        )
);

CREATE INDEX idx_matches_home_team_id
    ON matches (home_team_id);

CREATE INDEX idx_matches_away_team_id
    ON matches (away_team_id);